apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-controller
subjects:
- namespace: amq-operator-cluster
  kind: ServiceAccount
  name: default
