amq:
  name: amq-broker-rhel8

operator:
  scope: cluster #or namespace
  namespace: bprosa-cso-amq

subscription:
  name: amq-broker-rhel8
  channel: 7.10.x #this is mandatory
  installPlanApproval: Automatic #only Manual will work
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: #this is mandatory
