amq:
  name: amq-broker-rhel8
  operator:
    scope: cluster #or namespace
    namespace: amq-operator-cluster
    subscription:
      name: amq-broker-rhel8
      channel: 7.10.x
      installPlanApproval: Manual
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: amq-broker-operator.v7.10.2-opr-2
      allNamespaces: false
