{{- if .Values.operator }}
{{- if eq .Values.operator.scope "cluster" }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ print .Values.amq.name "-og" }}
spec: {}
{{- else if eq .Values.operator.scope "namespace"}}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ print .Values.amq.name "-og" }}
spec:
  targetNamespaces:
    - {{ .Values.operator.namespace }}
{{- end }}
{{- end }}